---
- name: Load VM vars
  include_vars: "vms.yml"
  tags:
   - always

- include: install-RedHat.yml
  when: "'kvm_servers' in group_names and ansible_distribution == 'CentOS'"
  tags:
    - install_kvm

- include: create-vm.yml
  when: "'kvm_servers' in group_names and ansible_distribution == 'CentOS'"
  with_items: "{{ virtual_machines }}"
  loop_control:
    loop_var: vm
  tags:
    - run_vms