---
graylog_root_data_dir: /opt/docker

mongodb_img_ver: 3 
mongodb_image: mongo:{{ mongodb_img_ver }}
mongodb_container_name: mongodb

elasticsearch_img_ver: 6.8.7
elasticsearch_image: elasticsearch:{{ elasticsearch_img_ver }}
elasticsearch_container_name: elasticsearch
elasticsearch_port: 9200

graylog_img_ver: latest
graylog_image: graylog/graylog:{{ graylog_img_ver }}
graylog_container_name: graylog3
graylog_http_bind_port: 9000
graylog_http_external_uri: https://graylog.host.name:{{ graylog_http_bind_port }}
graylog_tcp_port: 8514
graylog_udp_port: 8514
graylog_gelf_tcp_port: 12201
graylog_gelf_udp_port: 12201
graylog_beats_port: 5044