---
- name: Check if Uyuni Bootstrap repo is already added
  stat:
    path: /etc/apt/sources.list.d/susemanager_bootstrap.list
  register: salt_repo

- name: Copy Uyuni Bootstrap repo file for Ubuntu 18.04
  template:
    src: susemanager_bootstrap_18_04.list.j2
    dest: /etc/apt/sources.list.d/susemanager_bootstrap.list
    mode: 0644
  when: ansible_distribution_version == '18.04'

- name: Copy Uyuni Bootstrap repo file for Ubuntu 16.04
  template:
    src: susemanager_bootstrap_16_04.list.j2
    dest: /etc/apt/sources.list.d/susemanager_bootstrap.list
    mode: 0644
  when: ansible_distribution_version == '16.04'

- name: Copy Uyuni Bootstrap repo file for Ubuntu 20.04
  template:
    src: susemanager_bootstrap_20_04.list.j2
    dest: /etc/apt/sources.list.d/susemanager_bootstrap.list
    mode: 0644
  when: ansible_distribution_version == '20.04'

- name: Delete old machine-id files on Ubuntu
  file:
    path: "{{ item}}"
    state: absent
  with_items:
    - /var/lib/dbus/machine-id
    - /etc/machine-id

- name: Generate new machine-id on Ubuntu
  shell: systemd-machine-id-setup

- name: Check that old Salt master public key exists
  stat:
    path: /etc/salt/pki/minion/minion_master.pub
  register: oldmaster_key_result
  tags:
    - update_salt_conf

- name: Delete old Salt master public key
  file:
    path: /etc/salt/pki/minion/minion_master.pub
    state: absent
  when: oldmaster_key_result.stat.exists
  tags:
    - update_salt_conf

- name: Install salt-minion
  apt: 
    name: salt-minion
    state: latest
    update_cache: yes

- name: Disable all Ubuntu default repos
  replace:
    path: /etc/apt/sources.list
    regexp: '^(.*)$'
    replace: '# \1'

- name: Copy salt-minion config files
  template:
    src: salt-minion.conf.j2
    dest: /etc/salt/minion
    mode: 0644
  notify: salt_minion_restart systemd

- name: Copy salt-minion static grains conf
  template:
    src: grains.j2
    dest: /etc/salt/grains
    mode: 0644
  notify: salt_minion_restart systemd
  tags:
    - update_salt_conf

- name: Copy salt-minion Uyuni config
  template:
    src: susemanager.conf.j2
    dest: /etc/salt/minion.d/susemanager.conf
    mode: 0644
  notify: salt_minion_restart systemd
  tags:
    - update_salt_conf

- name: Copy salt-minion Uyuni config
  template:
    src: susemanager.conf.j2
    dest: /etc/salt/minion.d/susemanager.conf
    mode: 0644
  notify: salt_minion_restart systemd
  tags:
    - update_salt_conf