postgres_default_user: postgres
postgres_default_password: password
postgres_default_db: postgres

uyuni_manager_db_host: 127.0.0.1
uyuni_manager_db_name: susemanager
uyuni_manager_password: password
uyuni_manager_db_port: 5432
uyuni_manager_user: spacewalk
uyuni_manager_admin_email: admin@myserver.local
uyuni_cert_names: "{{ inventory_hostname }}"
uyuni_cert_o: O
uyuni_cert_ou: OU
uyuni_cert_city: City
uyuni_cert_state: State
uyuni_cert_country: Country
uyuni_cert_email: admin@myserver.local
uyuni_manager_db_backend: postgresql
uyuni_manager_db_protocol: TCP
uyuni_manager_enable_tftp: 1
uyuni_local_db: 1

## Salt/Uyuni Pillars
zabbix_mon_user: zabimon
zabbix_mon_password: password
