---
- include_vars: deps.yml
  when: ansible_facts['os_family'] == "Debian"
  tags:
    - install_graylog_sidecar
    
- name: Install a list of packages
  apt:
    name: '{{ item }}'
  with_items: '{{ packages }}'
  tags:
    - install_graylog_sidecar

- name: Install Graylog-sidecar
  apt:
    deb: https://github.com/Graylog2/collector-sidecar/releases/download/1.0.2/graylog-sidecar_{{ graylog_sidecar_ver }}_amd64.deb
  when: ansible_facts['os_family'] == "Debian"
  tags:
    - install_graylog_sidecar

- name: Copy Graylog-sidecar conf to server
  template:
    src: sidecar.yml.j2
    dest: /etc/graylog/sidecar/sidecar.yml
    owner:  root
    group: root
    mode: '0600'
  tags:
    - install_graylog_sidecar

- name: Create Graylog-sidecar systemd service
  command: graylog-sidecar -service install
  become: yes
  tags:
    - install_graylog_sidecar

- name: Purge previos Filebeat installation
  apt:
    name: filebeat
    purge: yes
    state: absent
  tags:
    - install_graylog_sidecar

- name: Recursively remove directory
  file:
    path: /etc/filebeat
    state: absent
  tags:
    - install_graylog_sidecar