---
- name: Create Docker data dir
  file:
    path: '{{ docker_datadir }}'
    state: directory
    owner: root
    group: root
    mode: '0700'
  tags:
   - docker_conf

- name: Update default docker.service file
  template:
    src: docker.service.j2
    dest: '/etc/systemd/system/docker.service'
    owner: root
    group: root
    mode: '0700'
  notify: 
    - reload systemd
    - restart docker
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'stretch'
  tags:
   - docker_conf

- name: Update default docker.service file
  template:
    src: docker.service.j2
    dest: '/lib/systemd/system/docker.service'
    owner: root
    group: root
    mode: '0644'
  notify: 
    - reload systemd
    - restart docker
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'buster'
  tags:
   - docker_conf

- name: Create Docker cleanup log dir
  file:
    path: '{{ docker_cleanup_script_dir }}/logs'
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags:
   - docker_conf

- name: Create docker_cleanup script
  template:
    src: docker_cleanup.sh.j2
    dest: '{{ docker_cleanup_script_dir }}/docker-cleanup.sh'
    owner: root
    group: root
    mode: '0700'
  tags:
   - docker_conf

- name: Create docker config
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  tags:
   - docker_conf

- name: Creates a cron file under /etc/cron.d for docker_cleanup task
  cron:
    name: Cleanup docker cache
    minute: "*/20"
    user: root
    job: "/opt/docker_cleanup/docker-cleanup.sh > /dev/null 2>&1"
    cron_file: docker_cleanup_task
  tags:
   - docker_conf
