---
- name: Load OS dependent variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags:
   - always

- name: Install a list of packages
  apt:
    name: '{{ item }}'
    state: latest
  with_items: '{{ packages }}'
  tags:
    - install_docker

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  tags:
    - install_docker

- name: Configure Docker's upstream APT repository
  apt_repository:
    repo: '{{ docker_apt_repository }}'
    update_cache: true
  tags:
    - install_docker

- name: Install Docker
  apt:
    name: "docker-{{ docker_edition }}"
    state: present
  tags:
    - install_docker