---
- name: Load OS dependent variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags:
   - always

- name: Install a list of packages
  yum:
    name: '{{ item }}'
    state: latest
  with_items: '{{ packages }}'
  tags:
    - install_docker

- name: Update the repository cache and install packages for HTTPS using
  yum:
    name: '{{ item }}'
    state: latest
    update_cache: yes
  with_items: '{{ packages }}'
  tags:
    - install_docker

- name: Add Docker's official GPG key
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present
  tags:
    - install_docker

- name: Add Docker repository
  get_url:
    url: "{{ docker_yum_repo_url }}"
    dest: '/etc/yum.repos.d/docker-{{ docker_edition }}.repo'
    owner: root
    group: root
    mode: 0644
  tags:
    - install_docker

- name: Install Docker
  yum:
    name: "docker-{{ docker_edition }}"
    state: present
  tags:
    - install_docker

- name: restart docker
  service:
    name: docker
    state: restarted
    enabled: yes