---
- name: Add the group for Azure Agents user
  user:
    name: '{{ azure_agent_group }}'
    state: present
  tags:
    - always

- name: Add the user for Azure Agents
  user:
    name: '{{ azure_agent_user }}'
    comment: Azure Agent
    home: '{{ azure_agent_dir }}'
    shell: /bin/false
    groups: docker, {{ azure_agent_group }}
  tags:
    - always

- name: Create Azure Agent directory
  file:
    path: '{{ azure_agent_dir }}/{{ item }}'
    state: directory
    owner: '{{ azure_agent_user }}'
    group: '{{ azure_agent_group }}'
    mode: '0750'
  tags:
    - always

# Azure DevOps agent wants libssl version 1.0.2
- name: "Install libssl1.0.2 for Debian 10"
  apt:
    deb: http://ftp.br.debian.org/debian/pool/main/o/openssl1.0/libssl1.0.2_1.0.2u-1~deb9u1_amd64.deb
  when: ansible_distribution == 'Debian' and ansible_distribution_version == '10'
  tags:
    - always
