---

- include_vars: ssl_servers.yml
  tags:
    - install_elasticsearch
    - install_config
    - install_CA

- debug: 
    msg: SSL hosts '{{ hosts }}'
  tags:
    - install_elasticsearch
    - install_config
    - install_CA

- include_vars: debian.yml
  when: ansible_facts['os_family'] == "Debian"
  tags:
    - install_elasticsearch

- name: Install a list of packages
  apt:
    name: '{{ item }}'
  with_items: '{{ packages }}'
  tags:
    - install_elasticsearch

- name: "Download Elasticsearch dep package and check checksum"
  get_url:
    url: 'https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elasticsearch_version }}-amd64.deb'
    dest: '/tmp/elasticsearch-{{ elasticsearch_version }}-amd64.deb'
    mode: '700'
    checksum: "{{ elasticsearch_deb_package_checksum }}"
  tags:
    - install_elasticsearch

- name: Install Elasticssearch
  apt: 
    deb: '/tmp/elasticsearch-{{ elasticsearch_version }}-amd64.deb'
  tags:
    - install_elasticsearch

- name: Create Elasticsearch data directory
  file:
    path: '{{ elasticsearch_data_dir }}'
    state: directory
    owner: '{{ elasticsearch_user }}'
    group: '{{ elasticsearch_group }}'
    mode: '0740'
  tags:
    - install_elasticsearch

- name: Create Elasticsearch ssl directory
  file:
    path: '{{ elasticsearch_ssl_dir }}'
    state: directory
    owner: root
    group: '{{ elasticsearch_group }}'
    mode: '0750'
  tags:
    - install_elasticsearch

- name: Copy Elasticsearch ssl servers list
  template:
    src: instances.file.j2
    dest: '{{ elasticsearch_ssl_dir }}/instances.yml'
    owner: root
    group: root
    mode: '0660'
    backup: yes
  tags:
    - install_elasticsearch
    - install_config
    - install_CA

- name: Copy Elasticsearch config to server
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner:  root
    group: '{{ elasticsearch_group }}'
    mode: '0660'
    backup: yes
  tags:
    - install_elasticsearch
    - install_config